### ISSUE TITLE
Some installer Issues with YAM 2.6p1

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#207]
**Originally by _opionline@yahoo.de_ on 2010-09-10 14:45:03 +0200**

___
I try to install YAM and found the follow issues:

1. I can't read the whole text in the installer Window. See picture YAM-InstallWindow-1.png. I Think i use a normal sized Font so the Text sould be shorter.
2. All '2.6' should be replaced by '2.6p1'!?
3. The german guide is not in the archive but i think the german guide is nearly up to date and should be included. It's IMHO better as no guide.
4. The Installer search for a directory MUI in the Install directory but it was not in the archive. Therefore i get a Error in line 798.
5. Same but for the Libs directory.
6. Same but for Libs/Charsets/ directory.
7. After the Errors in 4. 5. and 6. the Protokolldatei was deleted. :-(
8. The directories 'Rexx' and 'Themes' should contain the Files and not subdirectories with the same name.
9. After starting YAM2.6p1 i get some erros because of 8. and YAM search for updates. Here IMHO YAM should ask if the user want to search for updates. Not every user like Programs which does 'home calling' without permission.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-09-10 14:45:20 +0200**

___
**Attachment added:** `YAM-InstallWindow-1.png` (4.8 KiB)
![YAM-InstallWindow-1.png](https://yam.ch/attachments/207/YAM-InstallWindow-1.png)

**Comment by tboeckel** [comment]
**Originally on 2010-09-12 19:49:31 +0200**

___
#2, #4, #5, #6 and #8 have been addressed already, hence #9 should be fixed already as well.

Concerning #1, this is quite hard to fix, because we cannot know which font will be used on the individual systems and the window opened by Installer has a fixed size and there is no way to display a long text with a scrollbar attached. The text should be readable with topaz/8 as well as with any other not too big font, but we simply cannot change the window dimensions. The only solution would be to break up the text into two pages. But since the text has not changed since the 2.6 release (except the additional "p1" here and there) and the possible change would have to be done by several translators, too, it is unlikely this will be addressed. The benefit would be quite small. Another solution would be to used Guido Mersmann's MUI based Installer replacement (http://aminet.net/util/sys/Installer.lha). This one is able to resize its window and IIRC long texts are scrollable.

Concerning #3, the german guide was not included in the 2.6 release, because it is quite outdated by now being for YAM 2.4. I cannot estimate how much work has to be done to update it to 2.6, but it will definitely too much work until the scheduled release date in about 12 days.

I don't know if there can be a fix for #7, because everything concering a protocol file is done by the Installer application internally. The script doesn't even know if a file is created or not. Thus it cannot avoid deleting it for any reason.

**Comment by jens-maus** [comment]
**Originally by _opionline@yahoo.de_ on 2010-09-13 21:32:49 +0200**

___
The issue 8 is not yet fixed in the todays archive (13.09.2010).

Here the Installer create a directory 'rexx' in the install dir
and in this dir another 'rexx' Directory with all rexx files.

It the Files should go into the first 'rexx' Directory and the second
should not created (copied).

**Comment by tboeckel** [comment]
**Originally on 2010-09-15 08:34:15 +0200**

___
Ok, #8 is finally fixed now. I will upload new test archives as soon as I finished building them.
