### ISSUE TITLE
Crashes on "sent"

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/yam#301]
**Originally by _mario@cattaneo.de_ on 2012-05-12 12:25:32 +0200**

___
YAM 2.8-dev (12.05.2012)

When I trying sending a mail or pressing send to send complete outgoing YAM crashes.

GR log attached.

Haven't changed anything in my settings.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-05-12 12:26:13 +0200**

___
**Attachment added:** [`Crashlog_YAM_2012-05-12_12-00-03.txt`](https://yam.ch/attachments/301/Crashlog_YAM_2012-05-12_12-00-03.txt) (30.9 KiB)

**Comment by tboeckel** [comment]
**Originally on 2012-05-14 12:09:31 +0200**

___
This issue is most probably fixed with the next nightly build. Please reopen this ticket if not.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-05-15 14:30:05 +0200**

___
YAM 2.8-dev (15.05.2012)

Still crashing. Find new log attached.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-05-15 14:31:00 +0200**

___
**Attachment added:** [`Crashlog_YAM_2012-05-15_14-28-26.txt`](https://yam.ch/attachments/301/Crashlog_YAM_2012-05-15_14-28-26.txt) (28.3 KiB)

**Comment by tboeckel** [comment]
**Originally on 2012-05-15 15:03:36 +0200**

___
The next nightly build hopefully fixes this crash.

**Comment by jens-maus** [comment]
**Originally on 2012-05-17 11:25:15 +0200**

___
As there seems to be no further comment and other reports the problem with crashes on sending emails seems to be fixed.

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-05-17 15:40:14 +0200**

___
Why so impatient? Spare time is rare.

The problem persists (new log attached).

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-05-17 15:40:35 +0200**

___
**Attachment added:** [`Crashlog_YAM_2012-05-17_15-26-44.txt`](https://yam.ch/attachments/301/Crashlog_YAM_2012-05-17_15-26-44.txt) (29.2 KiB)

**Comment by jens-maus** [comment]
**Originally on 2012-05-17 16:07:54 +0200**

___
Ok. but I am sorry, we need more than just a crash log. so please grab the debug version of yam and provide a 'mail' debug log using the 'yamdebug' environment variable as explained in [[FAQ/Debugging]]

**Comment by tboeckel** [comment]
**Originally on 2012-06-10 20:10:59 +0200**

___
3 weeks have passed now. Any news?

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-06-11 23:17:14 +0200**

___
As I went back to an older beta (without the "multi id restriction") I didn't check this further.
I will install a current version to see, if something happend in the meantime.
Though, that will probably the last report by me then.
But I will check this last matter honoring  all the years of work together...

**Comment by jens-maus** [comment]
**Originally by _mario@cattaneo.de_ on 2012-06-19 18:03:49 +0200**

___
Ok, tried a recent beta and there seems to be no more crash.
So this can be closed.
